config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#welcome"

  get "/register", to: "users#new"
  get "/login", to: "users#login"
  post "/login", to: "users#login_user"
  delete '/login', to:  "users#logout"

  get "/auth/:provider/callback", to: "sessions#omniauth"

  resources :users, only: [:create, :show] do
    get "/past_trips", to: "users#past_trips", as: "past_trips"
    resources :trips, only: [:new, :create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :user_trips
  has_many :users, through: :user_trips
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_trips
  has_many :trips, through: :user_trips

  enum [:mother, :father, :partner, :sibling, :other]

  has_secure_password

  validates_presence_of :name, :email, :password, :on => :create
  validates_uniqueness_of :email
  
  def self.from_omniauth(response)
    user = User.find_by(email: response[:info][:email])
    if user
      user.update(uid: response[:uid], provider: response[:provider])
      user
    else
      User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u|
        u.name = response[:info][:name]
        u.email = response[:info][:email]
        u.password = SecureRandom.hex(15)
      end
    end
  end

  def upcoming_trips
    trips.where('end_time > ?', DateTime.now)
  end
end

app/models/user_trip.rb
class UserTrip < ApplicationRecord
  belongs_to :user
  belongs_to :trip
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @_current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def omniauth
    user = User.from_omniauth(request.env['omniauth.auth'])
    if user.valid?
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to '/login'
      flash[:error] = "Oops, it looks like that sign in method didn't work."
    end
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def new
    @user = current_user
  end

  def show
    @trip = Trip.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_attributes)
    if user.valid? && user_attributes[:password] == user_attributes[:password_confirmation]
      user.save
      session[:user_id] = user.id
      redirect_to user_path(user)
    elsif user.valid? && params[:password]!= params[:password_confirmation]
      flash[:error] = "Passwords do not match"
      redirect_to register_path
    else
      redirect_to register_path
      flash[:error] = user.errors.full_messages.join(", ")
    end
  end

  def show
    if session[:user_id] == params[:id].to_i
      @user = User.find(params[:id])
    else
      redirect_to root_path
      flash[:notice] = "You must be registered and logged in as the correct user to view this dashboard"
    end
  end

  def past_trips
    
  end

  def login
  end

  def login_user
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else user
      flash[:error] = "Incorrect email or password"
      redirect_to login_path
    end
  end

  def logout
    session.delete(:user_id)
    current_user = nil
    redirect_to root_path
  end

  private

  def user_attributes
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :emergency_contact_name, :emergency_contact_phone, :emergency_contact_relationship)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def welcome
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wandertrust</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to 'Wandertrust', root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item justify-content-end">
            <%if !current_user%>
              <%= link_to 'register', register_path, class: "nav-link" %>
            <%end%>
          </li>
          <li class="nav-item justify-content-end">
            <%if !current_user%>
              <%= link_to 'login', login_path, class: "nav-link" %>
            <%end%>
          </li>
          <li class="nav-item justify-content-end">
            <%if current_user%>
              <%= button_to '👋 logout', '/login', method: :delete, class: "nav-link" %>
            <%end%>
          </li>
          <li class="nav-item justify-content-end">
            <%if current_user%>
              <%= button_to '🏔️ my dashboard', user_path(current_user.id), method: :get, class: "nav-link" %>
            <%end%>
          </li>
          <li class="nav-item justify-content-end">
            <%if current_user%>
              <%= button_to '📍 new adventure', new_user_trip_path(current_user.id), method: :get, class: "nav-link" %>
            <%end%>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <br>
  <br>

    <%= yield %>
  </body>
</html>

app/views/trips/new.html.erb
<head>

  <script src='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.css' rel='stylesheet' />

</head>

<h1 class = "text-center">Create a New Trip</h1>

<div class = "container">
  <div class = "row justify-content-center align-items-center">
    <div class = "col-md-6 col-md-offset-3">
      <%= form_with url: user_trips_path(@user.id), method: :post do |f| %>
        <div class = "form-group">
          <%= f.label :name, "Trip Name:", class: "form-label" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class = "form-group">
          <%= f.label :start_time, "Start Time:", class: "form-label" %>
          <%= f.datetime_local_field :start_time, class: "form-control" %>
        </div>

        <div class = "form-group">
          <%= f.label :end_time, "Projected End Time:", class: "form-label" %>
          <%= f.datetime_local_field :end_time, class: "form-control" %>
        </div>

        <br>
        <br>

        <div class = "form-group">
        <h3>Upload a Route:</h3>
          <%= f.label :gpx_file, "GPX File" %>
          <%= f.file_field :gpx_file, class: "form-control", :accept => 'gpx'%>
        </div>
        <br>
        <br>

        <div id='map' style='width: 400px; height: 300px;'></div>
          <script>
            mapboxgl.accessToken = 'pk.eyJ1IjoidG9yaWVueWFydCIsImEiOiJjbGtpa29qbXgwaWJ3M2RucnMyM2Uyb3VvIn0.c70LlFDmTHKg3i6IqbfWnQ';
            var map = new mapboxgl.Map({
              container: 'map',
              style: 'mapbox://styles/mapbox/outdoors-v12',
              center: [-105.27, 40],
              zoom: 9
            });

            map.on('load', () => {
              map.addSource('route-tileset',{
                type: 'raster',
                tiles: [
                  'https://api.mapbox.com/v4/torienyart.ward_loop/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoidG9yaWVueWFydCIsImEiOiJjbGtpa29qbXgwaWJ3M2RucnMyM2Uyb3VvIn0.c70LlFDmTHKg3i6IqbfWnQ'
                ],
                tileSize: 256
              });

              map.addLayer({
                id: 'route-tileset-layer',
                type: 'raster',
                source: 'route-tileset',
                paint: {
                  'raster-opacity': .5
                }
              });
            });
          </script>


        <br>

        <div id="3rd-party-gpx" class="form-group">
          <%=button_to "Connect a Strava Route"  %>
          <br>
          <%=button_to "Connect a Ride With GPS Route"  %>
        </div>

        <br>

        <div class = "form-group">
          <%= f.submit "Create Trip", class: "btn btn-primary" %>
        </div>

      <% end %>
    </div>
  </div>

app/views/users/login.html.erb
<div class="container">
    <div class="row justify-content-center align-items-center min-vh-100">
      <div class="col-sm-6">
        <div id="login_buttons" class="card p-4">
          <h3 class="card-title text-center mb-4">Wandertrust Log In</h3>
          <%= form_with url: login_path, method: :post, class: "row g-3" do |f| %>
            <div class="col-md-12">
              <%= f.label :email, "Email Address:", class: "form-label" %>
              <%= f.text_field :email, class: "form-control" %>
            </div>
            <div class="col-md-12">
              <%= f.label :password, "Password:", class: "form-label" %>
              <%= f.password_field :password, class: "form-control" %>
            </div>
            <div class="col-md-12">
              <%= f.submit "Let's Wander", class: "btn btn-dark w-100 mb-3 text-white" %>
            </div>
          <% end %>
          <br>
          <div class="text-center">
            <%= button_to '/auth/google_oauth2' do %>
              <%= image_tag("btn_google_signin_dark_normal_web.png", alt: "Log In with Google") %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/users/new.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center min-vh-100">
    <div class="col-sm-6">
      <div class="card p-4">
        <h1 class="card-title text-center mb-4">🏔️ Wander With Us 🏔️</h1>
          <%= form_with model: @user, local: true, class: "row g-3" do |f|%>
            <%=f.label :name, "Name:"%>
            <%= f.text_field :name %>

            <%=f.label :email, "Email:"%>
            <%= f.text_field :email %>

            <%=f.label :password, "Password:"%>
            <%= f.password_field :password %>

            <%=f.label :password_confirmation, "Confirm Password:"%>
            <%= f.password_field :password_confirmation %>

            <div class="form-group row g-3 mb-4">
            <br>
            <br>
              <h3 class="text-center">Emergency Contact Information</h3>
              
              <%=f.label :emergency_contact_relationship, "Relationship:"%>
              <%= f.select :emergency_contact_relationship, options_for_select([["Select One", ""], "Mother", "Father", "Partner", "Sibling", "Other"]) %>

              <%=f.label :emergency_contact_name, "Full Name:"%>
              <%= f.text_field :emergency_contact_name %>

              <%=f.label :emergency_contact_phone, "Phone Number:"%>
              <%= f.text_field :emergency_contact_phone %>
            </div>
            <%= f.submit "Get Wandering", class: "btn btn-primary" %>

            <%end%>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="text-center">Welcome, <%=@user.name.split.first%>!</h1>
<div class="container-fluid" id="upcoming-trips">
  <h3>Here's what you've got coming up...</h3>
    <%@user.upcoming_trips.each do |trip|%>
      <div class="card" style="width: 18rem;" id="trip-<%=trip.id%>">
        <div class="card-body">
          <h5 class="card-title"><%=trip.name%></h5>
          <p>Start Time: <%=trip.start_time.strftime("%A, %B %d, %Y at %I:%M %p")%></p>
          <a class="btn btn-dark btn-center btn-md" href=<%=user_trip_path(@user.id, trip.id)%>>Trip Page</a>
        </div>
      </div>
    <%end%>
</div>

<div class="container-fluid" id="past_trips">
  <a class="btn btn-dark btn-center btn-md" href=<%=user_past_trips_path(@user.id)%>>Review Past Trips</a>
</div>

app/views/welcome/welcome.html.erb
<div class="d-flex justify-content-center">
    <%= image_tag("wandertrust_logo.png", width: "500") %>
</div>
<div class="text-center">
  <h6>Start tracking your adventures so you can trust where you wander...</h6>
  <br>
  <%if current_user%>
    <a class="btn btn-center btn-dark btn-md" href=<%=new_user_trip_path(current_user.id)%>>🏔️ let's wander 🏔️</a>
  <%else%>
    <a id="register-button" class="btn btn-center btn-dark btn-md" href=<%=register_path%>>🏔️ let's wander 🏔️</a>
  <%end%>
</div>